services:
  galacticabot:
    image: galacticabot
    build:
      context: .
      dockerfile: GalacticaBot/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GALACTICA_TOKEN=${GALACTICA_TOKEN}
    restart: unless-stopped
  galacticabot.api:
    image: galacticabot.api
    build:
      context: .
      dockerfile: GalacticaBot.Api/Dockerfile

