services:
  galacticabot:
    image: ghcr.io/jebediah47/galacticabot:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GALACTICA_TOKEN=${GALACTICA_TOKEN}
    restart: unless-stopped
